# -*- coffee -*- -p
author: YC <yinso.chen@gmail.com>
name: sexp-parser
description: A symbolic expression parser.
version: 0.1.0
repository:
  type: git
  url: git://bitbucket.org/yinso/sexp-parser.git
main: ./lib/main
engines:
  node: '>= 0.8.4'
scripts:
  test: make test
  prepublish: make
dependencies:
  yargs: =1.3.2
  coffee-script: =1.8.0
  underscore: =1.7.0
  loglet: '>=0.1.0'
  pegjs: =0.8.0
devDependencies:
  testlet: '>= 0.2.0'
  coffee-bean: =0.3.0
